sudo: required
services:
  - docker

before_install:
  - docker build -t mattaltepeter/frontend-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true mattaltepeter/frontend-demo npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'frontend-demo'
  env: 'frontenddemo-env'
  bucket_name: elasticbeanstalk-us-east-2-137735033005
  bucket_path: 'frontend-demo'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"